export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000/api';

export const STORAGE_KEYS = {
  TOKEN: 'auth_token',
  USER: 'auth_user',
} as const;

export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  FIGHTER_DASHBOARD: '/fighter/dashboard',
  FIGHTER_PROFILE: '/fighter/profile',
  FIGHTER_OPPONENTS: '/fighter/opponents',
  FIGHTER_REQUESTS: '/fighter/requests',
  FIGHTER_FIGHTS: '/fighter/fights',
  FIGHTER_SCHEDULED_FIGHTS: '/fighter/scheduled-fights',
  FIGHTER_FIGHT_OFFERS: '/fighter/fights/:fightId/offers',
  FIGHTER_FIGHT_HISTORY: '/fighter/fights/:fightId/history',
  FIGHTER_INJURIES: '/fighter/injuries',
  FIGHTER_MEDICAL_CLEARANCES: '/fighter/medical-clearances',
  FIGHTER_RANKINGS: '/fighter/rankings',
  PLO_DASHBOARD: '/plo/dashboard',
  PLO_EVENTS: '/plo/events',
  PLO_AVAILABLE_FIGHTS: '/plo/available-fights',
  PLO_OFFERS: '/plo/offers',
  PLO_PROFILE: '/plo/profile',
  SPECTATOR_HOME: '/spectator',
  SPECTATOR_EVENTS: '/spectator/events',
  SPECTATOR_RANKINGS: '/spectator/rankings',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PENDING_VERIFICATIONS: '/admin/pending-verifications',
  ADMIN_PENDING_VERIFICATION_DETAILS: '/admin/pending-verifications/:fighterId',
  ADMIN_PLOS: '/admin/promotion-leagues',
  ADMIN_EMAIL_VERIFICATION: '/admin/email-verification',
  ADMIN_MEDICAL_CLEARANCES: '/admin/medical-clearances',
  ADMIN_EVENT_CATEGORIES: '/admin/event-categories',
  ADMIN_WEIGHT_CLASSES: '/admin/weight-classes',
} as const;
